apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-prof-serivce
  labels:
    app: gestion-prof-serivce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gestion-prof-serivce
  template:
    metadata:
      namespace: prod
      name: gestion-prof-serivce
      labels:
        app: gestion-prof-serivce
    spec:
      containers:
        - name: gestion-prof-serivce
          image: elhadji01/gestion-prof-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
      