apiVersion: v1
kind: Service
metadata:
  name: gestion-prof-service
spec:
  selector:
    app: gestion-prof-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8083
  type: NodePort
  